name: Create Release

on:
  push:
    tags:
      - 'v*'  # Aciona quando uma tag começando com "v" é criada

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create ZIP file
      run: |
        zip -r isometric-perspective.zip scripts/* templates/* module.json
        mv isometric-perspective.zip release.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        files: release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
